#include<stdio.h>

int main()
{
    int A[5][10];
    int B[50];
    int A1 =sizeof A;
    int B1 = sizeof B;
    printf("size of A = %d\n",A1);
    printf("size of B = %d\n",B1);
    printf("2D Memory allocation\n");
    printf("%d\n",&A[0][0]);
    printf("%d\n",&A[0][1]);
    printf("%d\n",&A[0][2]);
    printf("%d\n",&A[0][3]);
    printf("%d\n",&A[0][4]);
    printf("%d\n",&A[0][5]);
    printf("%d\n",&A[0][6]);
    printf("%d\n",&A[0][7]);
    printf("%d\n",&A[0][8]);
    printf("%d\n",&A[0][9]);
    printf("%d\n",&A[1][0]);
    printf("%d\n",&A[1][1]);
    printf("%d\n",&A[1][2]);
    printf("%d\n",&A[1][3]);
    printf("%d\n",&A[1][4]);
    printf("%d\n",&A[1][5]);
    printf("%d\n",&A[1][6]);
    printf("%d\n",&A[1][7]);
    printf("%d\n",&A[1][8]);
    printf("%d\n",&A[1][9]);
    printf("%d\n",&A[2][0]);
    printf("%d\n",&A[2][1]);
    printf("%d\n",&A[2][2]);
    printf("%d\n",&A[2][3]);
    printf("%d\n",&A[2][4]);
    printf("%d\n",&A[2][5]);
    printf("%d\n",&A[2][6]);
    printf("%d\n",&A[2][7]);
    printf("%d\n",&A[2][8]);
    printf("%d\n",&A[2][9]);
    printf("%d\n",&A[3][0]);
    printf("%d\n",&A[3][1]);
    printf("%d\n",&A[3][2]);
    printf("%d\n",&A[3][3]);
    printf("%d\n",&A[3][4]);
    printf("%d\n",&A[3][5]);
    printf("%d\n",&A[3][6]);
    printf("%d\n",&A[3][7]);
    printf("%d\n",&A[3][8]);
    printf("%d\n",&A[3][9]);
    printf("%d\n",&A[4][0]);
    printf("%d\n",&A[4][1]);
    printf("%d\n",&A[4][2]);
    printf("%d\n",&A[4][3]);
    printf("%d\n",&A[4][4]);
    printf("%d\n",&A[4][5]);
    printf("%d\n",&A[4][6]);
    printf("%d\n",&A[4][7]);
    printf("%d\n",&A[4][8]);
    printf("%d\n",&A[4][9]);

    printf("1D Memory allocation\n");
    printf("%d\n",&B[0]);
    printf("%d\n",&B[1]);
    printf("%d\n",&B[2]);
    printf("%d\n",&B[3]);
    printf("%d\n",&B[4]);
    printf("%d\n",&B[5]);
    printf("%d\n",&B[6]);
    printf("%d\n",&B[7]);
    printf("%d\n",&B[8]);
    printf("%d\n",&B[9]);
    printf("%d\n",&B[10]);
    printf("%d\n",&B[11]);
    printf("%d\n",&B[12]);
    printf("%d\n",&B[13]);
    printf("%d\n",&B[14]);
    printf("%d\n",&B[15]);
    printf("%d\n",&B[16]);
    printf("%d\n",&B[17]);
    printf("%d\n",&B[18]);
    printf("%d\n",&B[19]);
    printf("%d\n",&B[20]);
    printf("%d\n",&B[21]);
    printf("%d\n",&B[22]);
    printf("%d\n",&B[23]);
    printf("%d\n",&B[24]);
    printf("%d\n",&B[25]);
    printf("%d\n",&B[26]);
    printf("%d\n",&B[27]);
    printf("%d\n",&B[28]);
    printf("%d\n",&B[29]);
    printf("%d\n",&B[30]);
    printf("%d\n",&B[31]);
    printf("%d\n",&B[32]);
    printf("%d\n",&B[33]);
    printf("%d\n",&B[34]);
    printf("%d\n",&B[35]);
    printf("%d\n",&B[36]);
    printf("%d\n",&B[37]);
    printf("%d\n",&B[38]);
    printf("%d\n",&B[39]);
    printf("%d\n",&B[40]);
    printf("%d\n",&B[41]);
    printf("%d\n",&B[42]);
    printf("%d\n",&B[43]);
    printf("%d\n",&B[44]);
    printf("%d\n",&B[45]);
    printf("%d\n",&B[46]);
    printf("%d\n",&B[47]);
    printf("%d\n",&B[48]);
    printf("%d\n",&B[49]);

}
